name: 'weekly'
description: 'Create new weekly issue, run weekly generator'
inputs:
  command:
    description: 'sub command to run'
    required: true
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
      - ${{ inputs.command }}